name: Build Project

on:
  push:
    branches:
      - main

jobs:
  retrieve-api-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve API key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "::set-env name=API_KEY::$API_KEY"
